"""SMARTS representations of the SynNet reactions.
Reference: https://github.com/wenhao-gao/SynNet/blob/master/data/rxn_set_hb.txt
"""
from reactions import (
    count_one_reagent,
    count_two_different_reagents,
    QueryMol,
    Reaction
)

# TODO: add reaction IDs that work alongside REAL reaction IDs
SYNNET_REACTIONS = [
    Reaction(
        reagents=[
            QueryMol('[c:1](-[C;$(C-c1ccccc1):2](=[OD1:3])-[OH1]):[c:4](-[NH2:5])'),
            QueryMol('[N;!H0;!$(N-N);!$(N-C=N);!$(N(-C=O)-C=O):6]-[C;H1,$(C-[#6]):7]=[OD1]')
        ],
        product=QueryMol('[c:4]2:[c:1]-[C:2](=[O:3])-[N:6]-[C:7]=[N:5]-2'),
        synnet_ids={8},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[CH0;$(C-[#6]):1]#[NH0:2]')
        ],
        product=QueryMol('[C:1]1=[N:2]-N-N=N-1'),
        synnet_ids={9},
        counting_fn=count_one_reagent
    ),
    Reaction(
        reagents=[
            QueryMol('[CH0;$(C-[#6]):1]#[NH0:2]'),
            QueryMol('[C;A;!$(C=O):3]-[*;#17,#35,#53]')
        ],
        product=QueryMol('[C:1]1=[N:2]-N(-[C:3])-N=N-1'),
        synnet_ids={10},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[CH0;$(C-[#6]):1]#[NH0:2]'),
            QueryMol('[C;A;!$(C=O):3]-[*;#17,#35,#53]')
        ],
        product=QueryMol('[C:1]1=[N:2]-N=N-N-1(-[C:3])'),
        synnet_ids={11},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[CH0;$(C-[#6]):1]#[CH1:2]'),
            QueryMol('[C;H1,H2;A;!$(C=O):3]-[*;#17,#35,#53,OH1]')
        ],
        product=QueryMol('[C:1]1=[C:2]-N(-[C:3])-N=N-1'),
        synnet_ids={12},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[CH0;$(C-[#6]):1]#[CH1:2]'),
            QueryMol('[C;H1,H2;A;!$(C=O):3]-[*;#17,#35,#53,OH1]')
        ],
        product=QueryMol('[C:1]1=[C:2]-N=NN(-[C:3])-1'),
        synnet_ids={13},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[CH0;$(C-[#6]):1]#[CH0;$(C-[#6]):2]'),
            QueryMol('[C;H1,H2;A;!$(C=O):3]-[*;#17,#35,#53,OH1]')
        ],
        product=QueryMol('[C:1]1=[C:2]-N=NN(-[C:3])-1'),
        synnet_ids={14},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[CH0;$(C-[#6]):1]#[NH0:2]'),
            QueryMol('[NH2:3]-[NH1:4]-[CH0;$(C-[#6]);R0:5]=[OD1]')
        ],
        product=QueryMol('[N:2]1-[C:1]=[N:3]-[N:4]-[C:5]=1'),
        synnet_ids={15},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[CH0;$(C-[#6]):1]#[NH0:2]'),
            QueryMol('[CH0;$(C-[#6]);R0:5](=[OD1])-[#8;H1,$(O-[CH3]),$(O-[CH2]-[CH3])]')
        ],
        product=QueryMol('[N:2]1-[C:1]=N-N-[C:5]=1'),
        synnet_ids={16},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[c:1](-[C;$(C-c1ccccc1):2](=[OD1:3])-[CH3:4]):[c:5](-[OH1:6])'),
            QueryMol('[C;$(C1-[CH2]-[CH2]-[N,C]-[CH2]-[CH2]-1):7](=[OD1])')
        ],
        product=QueryMol('[O:6]1-[c:5]:[c:1]-[C:2](=[OD1:3])-[C:4]-[C:7]-1'),
        synnet_ids={17},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[c;r6:1](-[C;$(C=O):6]-[OH1]):[c;r6:2]-[C;H1,$(C-C):3]=[OD1]'),
            QueryMol('[NH2:4]-[NH1;$(N-[#6]);!$(NC=[O,S,N]):5]')
        ],
        product=QueryMol('[c:1]1:[c:2]-[C:3]=[N:4]-[N:5]-[C:6]-1'),
        synnet_ids={18},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[C;$(C-c1ccccc1):1](=[OD1])-[C;D3;$(C-c1ccccc1):2]~[O;D1,H1]'),
            QueryMol('[CH1;$(C-c):3]=[OD1]')
        ],
        product=QueryMol('[C:1]1-N=[C:3]-[NH1]-[C:2]=1'),
        synnet_ids={19},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[NH1;$(N-c1ccccc1):1](-[NH2])-[c:5]:[cH1:4]'),
            QueryMol('[C;$(C([#6])[#6]):2](=[OD1])-[CH2;$(C([#6])[#6]);!$(C(C=O)C=O):3]')
        ],
        product=QueryMol('[C:5]1-[N:1]-[C:2]=[C:3]-[C:4]:1'),
        synnet_ids={20},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[*;Br,I;$(*c1ccccc1)]-[c:1]:[c:2]-[OH1:3]'),
            QueryMol('[CH1:5]#[C;$(C-[#6]):4]')
        ],
        product=QueryMol('[c:1]1:[c:2]-[O:3]-[C:4]=[C:5]-1'),
        synnet_ids={22},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[*;Br,I;$(*c1ccccc1)]-[c:1]:[c:2]-[SD2:3]-[CH3]'),
            QueryMol('[CH1:5]#[C;$(C-[#6]):4]')
        ],
        product=QueryMol('[c:1]1:[c:2]-[S:3]-[C:4]=[C:5]-1'),
        synnet_ids={23},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[*;Br,I;$(*c1ccccc1)]-[c:1]:[c:2]-[NH2:3]'),
            QueryMol('[CH1:5]#[C;$(C-[#6]):4]')
        ],
        product=QueryMol('[c:1]1:[c:2]-[N:3]-[C:4]=[C:5]-1'),
        synnet_ids={24},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[#6:6][C:5]#[#7;D1:4]'),
            QueryMol('[#6:1][C:2](=[OD1:3])[OH1]')
        ],
        product=QueryMol('[#6:6][c:5]1[n:4][o:3][c:2]([#6:1])n1'),
        synnet_ids={25},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[#6;H0;D3;$([#6](~[#6])~[#6]):1]B(O)O'),
            QueryMol('[#6;H0;D3;$([#6](~[#6])~[#6]):2][Cl,Br,I]')
        ],
        product=QueryMol('[#6:2][#6:1]'),
        synnet_ids={27},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[C;H1&$(C([#6])[#6]),H2&$(C[#6]):1][OH1]'),
            QueryMol('[NH1;$(N(C=O)C=O):2]')
        ],
        product=QueryMol('[C:1][N:2]'),
        synnet_ids={29},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[C;H1&$(C([#6])[#6]),H2&$(C[#6]):1][OH1]'),
            QueryMol('[OH1;$(Oc1ccccc1):2]')
        ],
        product=QueryMol('[C:1][O:2]'),
        synnet_ids={30},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[C;H1&$(C([#6])[#6]),H2&$(C[#6]):1][OH1]'),
            QueryMol('[NH1;$(N([#6])S(=O)=O):2]')
        ],
        product=QueryMol('[C:1][N:2]'),
        synnet_ids={31},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[#6;$(C=C-[#6]),$(c:c):1][Br,I]'),
            QueryMol('[Cl,Br,I][c:2]')
        ],
        product=QueryMol('[c:2][#6:1]'),
        synnet_ids={36},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[#6:1][C:2]#[#7;D1]'),
            QueryMol('[Cl,Br,I][#6;$([#6]~[#6]);!$([#6]([Cl,Br,I])[Cl,Br,I]);!$([#6]=O):3]')
        ],
        product=QueryMol('[#6:1][C:2](=O)[#6:3]'),
        synnet_ids={37},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[#6:1][C;H1,$([C]([#6])[#6]):2]=[OD1:3]'),
            QueryMol('[Cl,Br,I][#6;$([#6]~[#6]);!$([#6]([Cl,Br,I])[Cl,Br,I]);!$([#6]=O):4]')
        ],
        product=QueryMol('[C:1][#6:2]([OH1:3])[#6:4]'),
        synnet_ids={38},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[Cl,Br,I][c;$(c1:[c,n]:[c,n]:[c,n]:[c,n]:[c,n]:1):1]'),
            QueryMol('[N;$(NC)&!$(N=*)&!$([N-])&!$(N#*)&!$([ND3])&!$([ND4])&!$(N[c,O])&!$(N[C,S]=[S,O,N]),H2&$(Nc1:[c,n]:[c,n]:[c,n]:[c,n]:[c,n]:1):2]')
        ],
        product=QueryMol('[c:1][N:2]'),
        synnet_ids={42},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[c;$(c1[c;$(c[C,S,N](=[OD1])[*;R0;!OH1])]cccc1):1][C;$(C(=O)[O;H1])]'),
            QueryMol('[c;$(c1aaccc1):2][Cl,Br,I]')
        ],
        product=QueryMol('[c:1][c:2]'),
        synnet_ids={44},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[Cl:1][CH2:2]-[C$([CH](C)),C$(C(C)(C)):3]=[O:4]'),
            QueryMol('[OH:12]-[c:11]1[c:6][c:7][c:8][c:9][c:10]1-[CH:13]=[O:14]')
        ],
        product=QueryMol('[C:3](=[O:4])-[c:2]1[c:13][c:10]2[c:9][c:8][c:7][c:6][c:11]2[o:12]1'),
        synnet_ids={54},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[C$(C(#C)([CX4])):2]#[C$(C(#C)([CX4])):1]'),
            QueryMol('[N$(N(~N)([CX4])):5]~[N]~[N]')
        ],
        product=QueryMol('[c:2]1[c:1][n:5][n][n]1'),
        synnet_ids={58},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[C$(C(=C)([CX4])):2]=[C$(C(=C)([CX4])):1]'),
            QueryMol('[N$(N(~N)([CX4])):5]~[N]~[N]')
        ],
        product=QueryMol('[C:2]1[C:1][N:5][N]=[N]1'),
        synnet_ids={59},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[C$(C(=C)([CX4,OX2,NX3])([CX4,OX2,NX3])),C$([CH](=C)([CX4,OX2,NX3])),C$([CH2](=C)):1]=[C$(C(=C)([CX4,OX2,NX3])([CX4,OX2,NX3])),C$([CH](=C)([CX4,OX2,NX3])),C$([CH2](=C)):2]'),
            QueryMol('[C$(C(=C)([CX4,OX2,NX3])([CX4,OX2,NX3])),C$([CH](=C)([CX4,OX2,NX3])),C$([CH2](=C)):3]=[C$([C](=C)(C)([CX4,OX2,NX3])),C$([CH](=C)(C)):4]-[C$([C](=C)(C)([CX4,OX2,NX3])),C$([CH](=C)(C)):5]=[C$(C(=C)([CX4,OX2,NX3])([CX4,OX2,NX3])),C$([CH](=C)([CX4,OX2,NX3])),C$([CH2](=C)):6]')
        ],
        product=QueryMol('[C:1]1[C:2][C:3][C:4]=[C:5][C:6]1'),
        synnet_ids={60},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[C$(C(#C)([CX4,OX2,NX3])),C$([CH](#C)):1]#[C$(C(#C)([CX4,OX2,NX3])),C$([CH](#C)):2]'),
            QueryMol('[C$(C(=C)([CX4,OX2,NX3])([CX4,OX2,NX3])),C$([CH](=C)([CX4,OX2,NX3])),C$([CH2](=C)):3]=[C$([C](=C)(C)([CX4,OX2,NX3])),C$([CH](=C)(C)):4]-[C$([C](=C)(C)([CX4,OX2,NX3])),C$([CH](=C)(C)):5]=[C$(C(=C)([CX4,OX2,NX3])([CX4,OX2,NX3])),C$([CH](=C)([CX4,OX2,NX3])),C$([CH2](=C)):6]')
        ],
        product=QueryMol('[C:1]1=[C:2][C:3][C:4]=[C:5][C:6]1'),
        synnet_ids={61},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[CH:7](=[O:8])-[c:1]1[c:2][c:3][c:4][c:5][c:6]1'),
            QueryMol('[O:24]=[C:23](-[C:22](=[O:25])-[c:15]1[c:10][c:11][c:12][c:13][c:14]1)-[c:20]1[c:21][c:16][c:17][c:18][c:19]1')
        ],
        product=QueryMol('[nH:27]-1[c:7]([n:26][c:23]([c:22]-1[c:15]1[c:10][c:11][c:12][c:13][c:14]1)-[c:20]1[c:21][c:16][c:17][c:18][c:19]1)-[c:1]1[c:2][c:3][c:4][c:5][c:6]1'),
        synnet_ids={64},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[O$(O(C)([CX4])):8][C:7](=[O:9])[CH:6][C:5][C:4][C:3][C:2]([O$(O(C)([CX4])):10])=[O:1]')
        ],
        product=QueryMol('[O:8][C:7](=[O:9])[C:6]1[C:5][C:4][C:3][C:2]1=[O:1]'),
        synnet_ids={66},
        counting_fn=count_one_reagent
    ),
    Reaction(
        reagents=[
            QueryMol('[O$(O(C)([CX4])):8][C:7](=[O:9])[CH:6][C:5][C:11][C:4][C:3][C:2]([O$(O(C)([CX4])):10])=[O:1]')
        ],
        product=QueryMol('[O:8][C:7](=[O:9])[C:6]1[C:5][C:11][C:4][C:3][C:2]1=[O:1]'),
        synnet_ids={67},
        counting_fn=count_one_reagent
    ),
    Reaction(
        reagents=[
            QueryMol('[Cl:9][C:7](=[O:8])-[c:3]1[c:2][c:1][c:6][c:5][c:4]1'),
            QueryMol('[C$([CH2](C)([CX4])),C$([CH3](C)):18]-[C:16](=[O:17])-[c:14]1[c:13][c:12][c:11][c:10][c:15]1-[OH:19]')
        ],
        product=QueryMol('[O:17]=[C:16]-1-[C:18]=[C:7](-[O:8]-[c:15]2[c:10][c:11][c:12][c:13][c:14]-12)-[c:3]1[c:2][c:1][c:6][c:5][c:4]1'),
        synnet_ids={68},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[C$(C(C)(=O)([CX4,OX2&H0])),C$(C(C)(#N)),N$([N+1](C)(=O)([O-1])):1][C$([CH]([C,N])([C,N])([CX4])),C$([CH2]([C,N])([C,N])):2][C$(C(C)(=O)([CX4,OX2&H0])),C$(C(C)(#N)),N$([N+1](C)(=O)([O-1])):3]'),
            QueryMol('[C$(C(C)(#N)),C$(C(C)([CX4,OX2&H0])([CX4,OX2&H0])([OX2&H0])),C$([CH](C)([CX4,OX2&H0])([OX2&H0])),C$([CH2](C)([OX2&H0])),C$(C(C)(=O)([OX2&H0])):6][CH:5]=[C$(C(=C)([CX4])([CX4])),C$([CH](=C)([CX4])),C$([CH2](=C)):4]')
        ],
        product=QueryMol('[C:6][C:5][C:4][C:2]([C:1])[C:3]'),
        synnet_ids={69},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[C$([C](O)([CX4])([CX4])([CX4])),C$([CH](O)([CX4])([CX4])),C$([CH2](O)([CX4])):4]-[O:3]-[C$(C(=O)([CX4])),C$([CH](=O)):2]=[O:5]'),
            QueryMol('[C$([CH](C)([CX4])([CX4])),C$([CH2](C)([CX4])),C$([CH3](C)):7]-[C$(C(=O)([CX4])),C$([CH](=O)):8]=[O:9]')
        ],
        product=QueryMol('[C:7](-[C:2]=[O:5])-[C:8]=[O:9]'),
        synnet_ids={70},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[Cl,OH,O-:3][C$(C(=O)([CX4,c])),C$([CH](=O)):2]=[O:4]'),
            QueryMol('[O$([OH]([CX4,c])),O$([OH]([CX4,c])([CX4,c])),S$([SH]([CX4,c])),S$([SH]([CX4,c])([CX4,c])):6]')
        ],
        product=QueryMol('[*:6]-[C:2]=[O:4]'),
        synnet_ids={71},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[C$(C(=O)([CX4,c])([CX4,c])),C$([CH](=O)([CX4,c])):1]=[O:2]'),
            QueryMol('[N$([NH2,NH3+1]([CX4,c])),N$([NH]([CX4,c])([CX4,c])):3]')
        ],
        product=QueryMol('[N+0:3][C:1]'),
        synnet_ids={72},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[Br:1][c$(c(Br)),n$(n(Br)),o$(o(Br)),C$([CH](Br)(=C)):2]'),
            QueryMol('[C$(C(B)([CX4])([CX4])([CX4])),C$([CH](B)([CX4])([CX4])),C$([CH2](B)([CX4])),C$([CH2](B)),C$(C(B)(=C)),c$(c(B)),o$(o(B)),n$(n(B)):3][B$(B([C,c,n,o])([OH,$(OC)])([OH,$(OC)])),B$([B-1]([C,c,n,o])(N)([OH,$(OC)])([OH,$(OC)])):4]')
        ],
        product=QueryMol('[C,c,n,o:2][C,c,n,o:3]'),
        synnet_ids={73},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[Br,I:1][C$(C([Br,I])([CX4])([CX4])([CX4])),C$([CH]([Br,I])([CX4])([CX4])),C$([CH2]([Br,I])([CX4])),C$([CH3]([Br,I])),C$([C]([Br,I])(=C)([CX4])),C$([CH]([Br,I])(=C)),C$(C([Br,I])(#C)),c$(c([Br,I])):2]'),
            QueryMol('[Br,I:3][C$(C([Br,I])([CX4])([CX4])([CX4])),C$([CH]([Br,I])([CX4])([CX4])),C$([CH2]([Br,I])([CX4])),C$([CH3]([Br,I])),C$([C]([Br,I])(=C)([CX4])),C$([CH]([Br,I])(=C)),C$(C([Br,I])(#C)),c$(c([Br,I])):4]')
        ],
        product=QueryMol('[C,c:2][C,c:4]'),
        synnet_ids={74},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[OH,O-]-[C$(C(=O)(O)([CX4,c])):2]=[O:3]'),
            QueryMol('[OH:8]-[C$([CH](O)([CX4,c])([CX4,c])),C$([CH2](O)([CX4,c])),C$([CH3](O)):6]')
        ],
        product=QueryMol('[C:6][O]-[C:2]=[O:3]'),
        synnet_ids={75},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[C$([CH](=C)([CX4])),C$([CH2](=C)):2]=[C$(C(=C)([CX4])([CX4])),C$([CH](=C)([CX4])),C$([CH2](=C)):3]'),
            QueryMol('[Br,I:7][C$([CX4]([Br,I])),c$([c]([Br,I])):4]')
        ],
        product=QueryMol('[C,c:4][C:2]=[C:3]'),
        synnet_ids={76},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[Cl,OH,O-:3][C$(C(=O)([CX4,c])),C$([CH](=O)):2]=[O:4]'),
            QueryMol('[N$([NH2,NH3+1]([CX4,c])),N$([NH]([CX4,c])([CX4,c])):6]')
        ],
        product=QueryMol('[N+0:6]-[C:2]=[O:4]'),
        synnet_ids={77},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[I:1][C$(C(I)([CX4,c])([CX4,c])([CX4,c])),C$([CH](I)([CX4,c])([CX4,c])),C$([CH2](I)([CX4,c])),C$([CH3](I)):2]'),
            QueryMol('[C$(C(=O)([Cl,OH,O-])([CX4,c])),C$([CH]([Cl,OH,O-])(=O)):3](=[O:6])[Cl,OH,O-:5]')
        ],
        product=QueryMol('[C:2]-[C:3]=[O:6]'),
        synnet_ids={80},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[C$(C(C)([CX4])([CX4])([CX4])),C$([CH](C)([CX4])([CX4])),C$([CH2](C)([CX4])),C$([CH3](C)):1][C:2]#[CH:3]'),
            QueryMol('[Br,I:4][C$(C(=O)([Br,I])([CX4])),C$([CH](=O)([Br,I])):5]=[O:6]')
        ],
        product=QueryMol('[C:1][C:2]#[C:3][C:5]=[O:6]'),
        synnet_ids={83},
        counting_fn=count_two_different_reagents
    ),
    Reaction(
        reagents=[
            QueryMol('[OH,O-:4]-[C$(C(=O)([OH,O-])([CX4])),C$([CH](=O)([OH,O-])):2]=[O:3]')
        ],
        product=QueryMol('[Cl:5][C:2]=[O:3]'),
        synnet_ids={84},
        counting_fn=count_one_reagent
    ),
    Reaction(
        reagents=[
            QueryMol('[OH:2]-[$([CX4]),c:1]')
        ],
        product=QueryMol('[Br:3][C,c:1]'),
        synnet_ids={85},
        counting_fn=count_one_reagent
    ),
    Reaction(
        reagents=[
            QueryMol('[OH:2]-[$([CX4]),c:1]')
        ],
        product=QueryMol('[Cl:3][C,c:1]'),
        synnet_ids={86},
        counting_fn=count_one_reagent
    ),
    Reaction(
        reagents=[
            QueryMol('[OH,O-:3][S$(S([CX4])):2](=[O:4])=[O:5]')
        ],
        product=QueryMol('[Cl:6][S:2](=[O:5])=[O:4]'),
        synnet_ids={87},
        counting_fn=count_one_reagent
    ),
    Reaction(
        reagents=[
            QueryMol('[Cl,I,Br:7][c:1]1[c:2][c:3][c:4][c:5][c:6]1')
        ],
        product=QueryMol('[N:9]#[C:8][c:1]1[c:2][c:3][c:4][c:5][c:6]1'),
        synnet_ids={90},
        counting_fn=count_one_reagent
    )
]
